[General]
loglevel = warning
internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://cp.cloudflare.com/generate_204
proxy-test-udp = apple.com@1.1.1.1
test-timeout = 5
hijack-dns = *:53
ipv6 = false
ipv6-vif = disabled
skip-proxy = 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, ::1/128, fc00::/7, fe80::/10, localhost, *.local, captive.apple.com
exclude-simple-hostnames = true
read-etc-hosts = true
dns-server = 119.29.29.29, 223.5.5.5
# encrypted-dns-server = tls://223.5.5.5
geoip-maxmind-url = https://gh-proxy.org/https://github.com/lauyv/cnip/raw/rel/chnroutes.mmdb
udp-policy-not-supported-behaviour = REJECT
http-listen = 0.0.0.0
socks5-listen = 0.0.0.0
allow-wifi-access = false
allow-hotspot-access = false
show-error-page-for-reject = true

[Proxy]

[Proxy Group]
PROXY = smart,policy-path=https://nodelist
[Rule]
PROTOCOL,STUN,REJECT
DOMAIN-SET,https://gh-proxy.org/https://github.com/lauyv/rdat/raw/rel/reject.list,REJECT-DROP,pre-matching,extended-matching
DOMAIN-SET,https://gh-proxy.org/https://github.com/lauyv/rdat/raw/rel/loc-cn.list,DIRECT,extended-matching
GEOIP,CN,DIRECT
GEOIP,LAN,DIRECT
FINAL,PROXY,dns-failed

[Host]

[URL Rewrite]
^https?:\/\/www\.google\.cn https://www.google.com 302

[SSID Setting]

[MITM]
skip-server-cert-verify = true
h2 = true
hostname = www.google.cn
ca-passphrase = 
ca-p12 = 
